name: todo
description: Take-Home Challenge for Flutter Mobile Developer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  intl: ^0.17.0
  tapped: ^2.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  stream_transform: ^2.1.0
  fluttertoast: ^8.1.2
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  logger: ^1.1.0
  flutter_screenutil: ^5.6.1
  external_path: ^1.0.3
  csv: ^5.0.1
  open_file: ^3.2.1
  duration_picker: ^1.1.1
  provider: ^6.0.5
  easy_localization: ^3.0.1
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
